# -*-coding: utf-8 -*-

__title__ = "Details" #Name of the button displayed in Revit UI
__doc__   ="""This is simple tool to Copy Elemement With Revit API """ #Button Description shown in Revit UI
__version__ = "Version = 1.0"
__doc__ = """ Version = 1.0
Date    = 02.09.2023
_____________________________________________________________________
Description:

Test code about Get all Furniture and Plumbing elements and write Room's name
if available to a comment Parameter.
______________________________________
Author: Dmytro Khom"""
__author__ = "Dmytro Khom"




# ‚ï¶‚ïî‚ï¶‚ïó‚ïî‚ïê‚ïó‚ïî‚ïê‚ïó‚ï¶‚ïê‚ïó‚ïî‚ï¶‚ïó‚ïî‚ïê‚ïó
# ‚ïë‚ïë‚ïë‚ïë‚ï†‚ïê‚ïù‚ïë ‚ïë‚ï†‚ï¶‚ïù ‚ïë ‚ïö‚ïê‚ïó
# ‚ï©‚ï© ‚ï©‚ï©  ‚ïö‚ïê‚ïù‚ï©‚ïö‚ïê ‚ï© ‚ïö‚ïê‚ïù IMPORTS
# =======================================================================

# Regular + Autodesk
# from Autodesk.Revit.DB import *    #Import everything from DB (Very good for beginners and development)
# from Autodesk.Revit.UI import UIDocument, UIApplication

import os
location = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__)))
file = os.path.realpath(os.path.join(location + '/log.txt'))
from datetime import datetime

from rpw import revit
user = revit.username
with open(file, mode='a+') as csv_file:
	csv_file.writelines(str(user) + ' ' + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + '\n')
import clr
import sys
from System.Collections.Generic import *
__persistentengine__ = True
import Autodesk
from Autodesk.Revit.UI import IExternalEventHandler, IExternalApplication, Result, ExternalEvent, IExternalCommand, TaskDialog
from Autodesk.Revit.DB import Transaction
from Autodesk.Revit.Exceptions import InvalidOperationException, OperationCanceledException, ArgumentException
import rpw
from rpw import revit, DB, UI
from pyrevit.forms import WPFWindow
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI import *
from Autodesk.Revit.UI.Selection import *
from Autodesk.Revit.Exceptions import *


# ‚ï¶  ‚ï¶‚ïî‚ïê‚ïó‚ï¶‚ïê‚ïó‚ï¶‚ïî‚ïê‚ïó‚ïî‚ïó ‚ï¶  ‚ïî‚ïê‚ïó‚ïî‚ïê‚ïó
# ‚ïö‚ïó‚ïî‚ïù‚ï†‚ïê‚ï£‚ï†‚ï¶‚ïù‚ïë‚ï†‚ïê‚ï£‚ï†‚ï©‚ïó‚ïë  ‚ïë‚ï£ ‚ïö‚ïê‚ïó
#  ‚ïö‚ïù ‚ï© ‚ï©‚ï©‚ïö‚ïê‚ï©‚ï© ‚ï©‚ïö‚ïê‚ïù‚ï©‚ïê‚ïù‚ïö‚ïê‚ïù‚ïö‚ïê‚ïù VARIABLES
# ===========================================================================
# from pyrevit.revit import uidoc, doc, app #Alternative
doc    = __revit__.ActiveUIDocument.Document   #type: UIDocument
uidoc  = __revit__.ActiveUIDocument            #type: Document
app    = __revit__.Application                 #type: UIApplication



# ‚ïî‚ïê‚ïó‚ï¶ ‚ï¶‚ïî‚ïó‚ïî‚ïî‚ïê‚ïó‚ïî‚ï¶‚ïó‚ï¶‚ïî‚ïê‚ïó‚ïî‚ïó‚ïî‚ïî‚ïê‚ïó
# ‚ï†‚ï£ ‚ïë ‚ïë‚ïë‚ïë‚ïë‚ïë   ‚ïë ‚ïë‚ïë ‚ïë‚ïë‚ïë‚ïë‚ïö‚ïê‚ïó
# ‚ïö  ‚ïö‚ïê‚ïù‚ïù‚ïö‚ïù‚ïö‚ïê‚ïù ‚ï© ‚ï©‚ïö‚ïê‚ïù‚ïù‚ïö‚ïù‚ïö‚ïê‚ïù FUNCTIONS
# ===========================================================================
class CustomizableEvent:
	def __init__(self):
		""" An instance of this class need to be created before any modeless operation.
		You can then call the raise_event method to perform any modeless operation.
		Any modification to Revit DB need to be performed inside a valid Transaction.
		This Transaction needs to be open inside the function_or_method, NOT before calling raise_event.
		>>> customizable_event = CustomizableEvent()
		>>> customizable_event.raise_event(rename_views, views_and_names)
		"""
		# Create an handler instance and his associated ExternalEvent
		custom_handler = _CustomHandler()
		custom_handler.customizable_event = self
		self.custom_event = UI.ExternalEvent.Create(custom_handler)

		# Initialise raise_event variables
		self.function_or_method = None
		self.args = ()
		self.kwargs = {}

	def _raised_method(self):
		""" !!! DO¬†NOT¬†USE THIS METHOD IN¬†YOUR¬†SCRIPT !!!
		Method executed by IExternalEventHandler.Execute when ExternalEvent is raised by ExternalEvent.Raise.
		"""
		self.function_or_method(*self.args, **self.kwargs)

	def raise_event(self, function_or_method, *args, **kwargs):
		"""
		Method used to raise an external event with custom function and parameters
		Example :
		>>> customizable_event = CustomizableEvent()
		>>> customizable_event.raise_event(rename_views, views_and_names)
		"""
		self.args = args
		self.kwargs = kwargs
		self.function_or_method = function_or_method
		self.custom_event.Raise()

class _CustomHandler(UI.IExternalEventHandler):
	""" Subclass of IExternalEventHandler intended to be used in CustomizableEvent class
	Input : function or method. Execute input in a IExternalEventHandler"""
	def __init__(self):
		self.customizable_event = None

	# Execute method run in Revit API environment.
	# noinspection PyPep8Naming, PyUnusedLocal
	def Execute(self, application):
		try:
			self.customizable_event._raised_method()
		except InvalidOperationException:
			# If you don't catch this exeption Revit may crash.
			print "InvalidOperationException catched"

	# noinspection PyMethodMayBeStatic, PyPep8Naming
	def GetName(self):
		return "Execute an function or method in a IExternalHandler"


customizable_event = CustomizableEvent()


# üü¢ WPF FUNCTION
class ModelessForm(WPFWindow):

	def __init__(self, xaml_file_name):
		WPFWindow.__init__(self, xaml_file_name)
		self.out_list = None
		self.Show()

	def write_filter(self):
		doc = __revit__.ActiveUIDocument.Document
		t=Transaction(doc, '–í—ñ–¥–æ–º–æ—Å—Ç—ñ')
		t.Start()
		els = [ doc.GetElement( elId ) for elId in uidoc.Selection.GetElementIds() ]

		# üíö INFORMATION FROM WINDONDOW
		if len(els) > 0:
			if str(els[0].Category.Id) == '-2000510':
				filter_status = '0'
				for e in FilteredElementCollector(doc, els[0].ViewId).OfCategory(BuiltInCategory.OST_DetailComponents).WhereElementIsNotElementType().ToElements():
					e_type = doc.GetElement(e.GetTypeId())
					det_fam_name = e_type.get_Parameter(BuiltInParameter.ALL_MODEL_FAMILY_NAME).AsString()
					if det_fam_name == '–î–µ—Ç0':
						if self.radio_1.IsChecked:
							filter_type = 'marka'
						elif self.radio_2.IsChecked:
							filter_type = 'mrkcon'
						elif self.radio_3.IsChecked:
							filter_type = 'mrkizd'
						#TaskDialog.Show('er','er2')
						change_com = ('{}*/{}*/{}*/{}').format(self.Filter_value.Text,
															   filter_type, str(self.One_construction_check.IsChecked),
															   str(self.Arm_vupysk_check.IsChecked))
						filter_status = e.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS).Set(change_com)
						#TaskDialog.Show('er','er3')
						compl_draw = els[0].LookupParameter('–û—Ä–≥.–ö–æ–º–ø–ª–µ–∫—Ç–ö—Ä–µ—Å–ª–µ–Ω—å').Set(self.Complect_value.Text)
						vidm_draw = els[0].LookupParameter('–û—Ä–≥.–í—ñ–¥–º—ñ—Ç–∫–∞').Set(self.Elevation_value.Text)
						view_name = els[0].get_Parameter(BuiltInParameter.VIEW_NAME).Set(self.Name_value.Text + '_–í—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π')
						#TaskDialog.Show('er','er4')
			else:
				TaskDialog.Show('error', '–í–∏–±–µ—Ä—ñ—Ç—å –≤—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π')

		else:
			TaskDialog.Show('error', '–í–∏–±–µ—Ä—ñ—Ç—å –≤—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π')
		t.Commit()

	def read_filter(self):
		doc = __revit__.ActiveUIDocument.Document
		#TaskDialog.Show('er','1')
		els = [ doc.GetElement( elId ) for elId in uidoc.Selection.GetElementIds() ]
		if len(els) > 0:
			if str(els[0].Category.Id) == '-2000510':
				view_name = els[0].get_Parameter(BuiltInParameter.VIEW_NAME).AsString()
				#TaskDialog.Show('er','2')
				if '_' in view_name:
					mark_name = view_name.split('_')[0]
				else:
					mark_name = error
				compl_draw = els[0].LookupParameter('–û—Ä–≥.–ö–æ–º–ø–ª–µ–∫—Ç–ö—Ä–µ—Å–ª–µ–Ω—å').AsString()
				vidm_draw = els[0].LookupParameter('–û—Ä–≥.–í—ñ–¥–º—ñ—Ç–∫–∞').AsString()
				for e in FilteredElementCollector(doc, els[0].ViewId).OfCategory(BuiltInCategory.OST_DetailComponents).WhereElementIsNotElementType().ToElements():
					e_type = doc.GetElement(e.GetTypeId())
					det_fam_name = e_type.get_Parameter(BuiltInParameter.ALL_MODEL_FAMILY_NAME).AsString()
					if det_fam_name == '–î–µ—Ç0':

						#newdet=doc.Create.NewFamilyInstance(XYZ(0,0,0), r0, detail_create)
						filter_status = e.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS).AsString()
						if len(filter_status.split('*/')) == 4:

							filter_type = filter_status.split('*/')[1]
							one_cons = filter_status.split('*/')[2]
							s_filter = filter_status.split('*/')[0]
							arm_vup_check = filter_status.split('*/')[3]
							self.Complect_value.Text = compl_draw
							self.Elevation_value.Text = vidm_draw
							self.Name_value.Text = mark_name
							self.Filter_value.Text = s_filter

							if one_cons == 'True':
								self.One_construction_check.IsChecked = True
							else:
								self.One_construction_check.IsChecked = False
							if arm_vup_check == 'True':
								self.Arm_vupysk_check.IsChecked = True
							else:
								self.Arm_vupysk_check.IsChecked = False
							if filter_type == 'marka':
								self.radio_1.IsChecked = True
							elif filter_type == 'mrkcon':
								self.radio_2.IsChecked = True
							elif filter_type == 'mrkizd':
								self.radio_3.IsChecked = True

			else:
				TaskDialog.Show('error', '–í–∏–±–µ—Ä—ñ—Ç—å –≤—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π')
		else:
			TaskDialog.Show('error', '–í–∏–±–µ—Ä—ñ—Ç—å –≤—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π')

	def create_detail(self, status):
		status = status[0]

		uidoc = __revit__.ActiveUIDocument
		doc = __revit__.ActiveUIDocument.Document
		curview = uidoc.ActiveGraphicalView

		s_name = ('{}*/{}*/{}').format(self.Complect_value.Text,self.Elevation_value.Text,self.Name_value.Text)
		s_filter = self.Filter_value.Text
		if self.radio_1.IsChecked:
			filter_type = 'marka'
		elif self.radio_2.IsChecked:
			filter_type = 'mrkcon'
		elif self.radio_3.IsChecked:
			filter_type = 'mrkizd'
		one_cons = self.One_construction_check.IsChecked
		arm_vupysk = self.Arm_vupysk_check.IsChecked
		exit_error = False
		if not isinstance(curview, ViewSheet):
			exit_error = True
			TaskDialog.Show('error', '–ó–∞–π–¥—ñ—Ç—å –Ω–∞ –∞—Ä–∫—É—à')
		t=Transaction(doc, '–í—ñ–¥–æ–º–æ—Å—Ç—ñ')
		t.Start()
		position_list = []
		if status == 'refresh':

			els = [ doc.GetElement( elId ) for elId in uidoc.Selection.GetElementIds() ]

			if len(els) > 0:
				if str(els[0].Category.Id) == '-2000510':
					detail_create = doc.GetElement(els[0].ViewId)

					filter_status = '0'
					for e in FilteredElementCollector(doc, detail_create.Id).OfCategory(BuiltInCategory.OST_DetailComponents).WhereElementIsNotElementType().ToElements():
						e_type = doc.GetElement(e.GetTypeId())
						det_fam_name = e_type.get_Parameter(BuiltInParameter.ALL_MODEL_FAMILY_NAME).AsString()
						if det_fam_name == '–î–µ—Ç0':
							#newdet=doc.Create.NewFamilyInstance(XYZ(0,0,0), r0, detail_create)
							filter_status = e.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS).AsString()

						else:
							num_mark = e.LookupParameter('–ê—Ä–º_–ú–∞—Ä–∫–∞').AsString()
							if len(str(num_mark))==1: #–¥–æ–¥–∞–º 0 –≤ –º–∞—Ä–∫–∏ –≤—ñ–¥ 1 –¥–æ 9 –¥–ª—è —Å–æ—Ä—Ç—É–≤–∞–Ω–Ω—è
								num_mark=str('0'+ num_mark)
							position_list.append([e.Location.Point, num_mark])
							doc.Delete(e.Id)
					#print(filter_status)
					if len(filter_status.split("*/")) >= 3:
						filter_type = filter_status.split('*/')[1]
						one_cons = filter_status.split('*/')[2]
						s_filter = filter_status.split('*/')[0]
						arm_vupysk = 'False'
					if len(filter_status.split("*/")) == 4:
						arm_vupysk = filter_status.split('*/')[3]
					if filter_status == '0':
						exit_error = True
						TaskDialog.Show('error', '–ù–µ –∑–∞–¥–∞–Ω—ñ –ø–∞—Ä–∞–º–µ—Ç—Ä–∏ —Å—ñ–º–µ–π—Å—Ç–≤–∞')
					#TaskDialog.Show('1', )
				else:
					TaskDilog.Show('error', '–í–∏–±–µ—Ä—ñ—Ç—å –≤–∏–¥–æ–≤–∏–π –µ–∫—Ä–∞–Ω –Ω–∞ –∞—Ä–∫—É—à—ñ')
					exit_error = True
			else:
				TaskDialog.Show('error', '–í–∏–±–µ—Ä—ñ—Ç—å –≤—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π')
				exit_error = True


		if not exit_error:
			rebar_list=[]
			rebar_shapes=[]
			rebar_type=[]
			rebar_mark=[]
			rebar_osn=[]
			#armA_l=[]
			#armB_l=[]
			#armV_l=[]
			#armG_l=[]
			#armK_l=[]
			result=[]
			#TaskDialog.Show('3',s_filter)
			rebar_filter = ElementCategoryFilter(BuiltInCategory.OST_Rebar)

			rebars = FilteredElementCollector(doc).WherePasses(rebar_filter).WhereElementIsNotElementType().ToElements()
			det_comp = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_DetailComponents).WhereElementIsElementType().ToElements()
			sheets = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Sheets).WhereElementIsNotElementType().ToElements()

			wall = [ doc.GetElement( elId ) for elId in uidoc.Selection.GetElementIds() ]

			name_wall=s_filter#wall[0].LookupParameter('–ú—Ä–∫.–ú–∞—Ä–∫–∞–ö–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏').AsString()

			list_names=[]
			arm_a_set=0
			arm_b_set=0
			arm_v_set=0
			arm_g_set=0
			arm_d_set=0
			arm_e_set=0
			arm_j_set=0
			arm_mark=0
			arm_alpha=0

			def arm_param(name, i):
				global arm_a_set, arm_b_set, arm_v_set, arm_g_set, arm_d_set, arm_e, arm_j, arm_mark, arm_alpha
				arm_mark=i[3]
				arm_a_set=i[4]
				arm_b_set=i[5]
				arm_v_set=i[6]
				arm_g_set=i[7]
				arm_d_set=i[8]
				arm_e_set=i[9]
				arm_j_set=i[10]
				arm_alpha=i[11]
			def det_line(det_name):
				for det in det_comp:
					det_r = det.get_Parameter(BuiltInParameter.ALL_MODEL_FAMILY_NAME)
					name = det_r.AsString()
					list_names.append(name)
					if name==det_name:
						detail_line=det
						break
				try:
					return detail_line
				except:
					return 0

			if len(s_filter)==0 and status != 'refresh': #—è–∫—â–æ –Ω–µ–º–∞—î —Ñ—ñ–ª—å—Ç—Ä—É
				ids = uidoc.Selection.GetElementIds()
				if isinstance(ids, list) == True:
					ids=[ids]
				list=[]
				for id in ids:
					el = doc.GetElement(id)
					name = el.GetType().Name
					#stage = el.get_Parameter(BuiltInParameter.PHASE_CREATED)
					#stage_name = stage.AsString()
					if name!="Rebar":
						list.append(id)

				list1 = List[ElementId]()
				for rebar in rebars:
					try:
						el_id = rebar.GetHostId()
					except:
						0
					for id in list:
						if id==el_id:
							list1.Add(rebar.Id)
				rebars_1 = uidoc.Selection.SetElementIds(list1)

				#----------------------------------------------------------

				rebars = [ doc.GetElement( elId ) for elId in uidoc.Selection.GetElementIds() ]
			else:	#—è–∫—â–æ –∑–∞–¥–∞–Ω–∏–π —Ñ—ñ–ª—å—Ç—Ä
				rebar_f = []
				#TaskDialog.Show('1', str(s_filter))
				for rebar in rebars:
					#try:
					r_type = doc.GetElement(rebar.GetTypeId())
					family = r_type.LookupParameter('–ê—Ä–º.–í—ã–ø–æ–ª–Ω–µ–Ω–∞–°–µ–º–µ–π—Å—Ç–≤–æ–º').AsValueString()
					#except:
					#	0#family = rebar.LookupParameter('–ê—Ä–º.–í—ã–ø–æ–ª–Ω–µ–Ω–∞–°–µ–º–µ–π—Å—Ç–≤–æ–º').AsValueString()

					if family == '–ù–µ—Ç':
						if filter_type == 'marka':
							mitka = rebar.get_Parameter(BuiltInParameter.REBAR_ELEM_HOST_MARK).AsString()

						elif filter_type == 'mrkcon':
							mitka = rebar.LookupParameter('–ú—Ä–∫.–ú–∞—Ä–∫–∞–ö–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏').AsString()
						elif filter_type == 'mrkizd':
							mitka = rebar.LookupParameter('–ú—Ä–∫.–ú–∞—Ä–∫–∞–ò–∑–¥–µ–ª–∏—è')
							if mitka != None:
								mitka = mitka.AsString()
							else:
								mitka = None
					else:
						if filter_type == 'marka':
							mitka = rebar.LookupParameter('–ú—Ä–∫.–ú–∞—Ä–∫–∞–ö–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏').AsString()
						elif filter_type == 'mrkcon':
							mitka = rebar.LookupParameter('–ú—Ä–∫.–ú–∞—Ä–∫–∞–ö–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏').AsString()
						elif filter_type == 'mrkizd':
							mitka = rebar.LookupParameter('–ú—Ä–∫.–ú–∞—Ä–∫–∞–ò–∑–¥–µ–ª–∏—è')
							if mitka != None:
								mitka = mitka.AsString()
							else:
								mitka = None
					stage = rebar.get_Parameter(BuiltInParameter.PHASE_CREATED)
					stage_name = stage.AsValueString()
					#print(one_cons)
					arm_pruzn = rebar.LookupParameter('–ê—Ä–º.–ü—Ä–∏–∑–Ω–∞—á–µ–Ω–Ω—è')
					#print(1)
					if arm_pruzn != None and arm_pruzn != 'None':
						arm_pruzn = arm_pruzn.AsString()
					else:
						arm_pruzn = 'ran'
						#arm_vupysk = False
					if one_cons == True or one_cons == 'True':
						#print(3)

						if mitka == s_filter and stage_name == '–ü—ñ–¥—Ä–∞—Ö—É–Ω–æ–∫ –Ω–∞ 1 –∫–æ–Ω—Å—Ç—Ä—É–∫—Ü—ñ—é':
							if arm_vupysk == 'True' or arm_vupysk == True:
								if str(arm_pruzn).lower() != '–≤–∏–ø—É—Å–∫–∏':
									#print(2)
									rebar_f.append(rebar)
							else:
								rebar_f.append(rebar)
							#print(4)
					else:
						if mitka == s_filter:
							#try:
							if arm_vupysk == 'True' or arm_vupysk == True:
								if str(arm_pruzn).lower() != '–≤–∏–ø—É—Å–∫–∏':

									rebar_f.append(rebar)
								#else:
								#    print(arm_pruzn)
							else:
								rebar_f.append(rebar)
							#except:
							#    0
				rebars=rebar_f
			mark_list=[]

			#TaskDialog.Show('1', str(len(rebars)))
			for rebar in rebars:

				try:
					try: #—Å–∏—Å—Ç–µ–º–Ω–∞ –∞—Ä–º–∞—Ç—É—Ä–∞
						sh=rebar.get_Parameter(BuiltInParameter.REBAR_SHAPE).AsValueString()
						if ' ' in sh:
							sh = sh.split(' ')[0]
							#print(sh)
						type = rebar.get_Parameter(BuiltInParameter.REBAR_BAR_DIAMETER).AsValueString()
						type=type.split(' ')[0]
						mark = rebar.get_Parameter(BuiltInParameter.ALL_MODEL_MARK).AsString()
						#print(mark)
						#mark_list.append(mark)
						if len(str(mark))==1: #–¥–æ–¥–∞–º 0 –≤ –º–∞—Ä–∫–∏ –≤—ñ–¥ 1 –¥–æ 9 –¥–ª—è —Å–æ—Ä—Ç—É–≤–∞–Ω–Ω—è
							mark=str('0'+ mark)
						#print('+')
						#print(mark)

					except: #IFC –∞—Ä–º–∞—Ç—É—Ä–∞
						sh = rebar.LookupParameter('–ê—Ä–º.–§–æ—Ä–º–∞').AsString()
						type = rebar.LookupParameter('–†–∑–º.–î–∏–∞–º–µ—Ç—Ä').AsString()
						mark = rebar.get_Parameter(BuiltInParameter.ALL_MODEL_MARK).AsString()
						if len(str(mark))==1: #–¥–æ–¥–∞–º 0 –≤ –º–∞—Ä–∫–∏ –≤—ñ–¥ 1 –¥–æ 9 –¥–ª—è —Å–æ—Ä—Ç—É–≤–∞–Ω–Ω—è
							mark=str('0'+ mark)
					try:
						armA = str(int(5*(round(int(rebar.LookupParameter('–ê—Ä–º_–ê').AsValueString())/5))))
						#armA_l.append(armA)
					except:
						armA = '0'
					try:
						armB = str(int(5*(round(int(rebar.LookupParameter('–ê—Ä–º_–ë').AsValueString())/5))))
						#armB_l.append(armB)
					except:
						armB='0'
						#armB_l.append('0')
					try:
						armV = str(int(5*(round(int(rebar.LookupParameter('–ê—Ä–º_–í').AsValueString())/5))))
					except:
						armV='0'
						#armV_l.append('0')
					try:
						armG = str(int(5*(round(int(rebar.LookupParameter('–ê—Ä–º_–ì').AsValueString())/5))))
						if sh=='26':
							armG = str(int(1*(round(int(rebar.LookupParameter('–ê—Ä–º_–ì').AsValueString())/1))))
							armG=str(int(float(armG)-float(type)))
					except:
						armG='0'
						#armG_l.append('0')
					try:
						armD = str(int(5*(round(int(rebar.LookupParameter('–ê—Ä–º_–î').AsValueString())/5))))
					except:
						armD = '0'
					try:
						armE = str(int(5*(round(int(rebar.LookupParameter('–ê—Ä–º_E').AsValueString())/5))))
					except:
						armE = '0'
					try:
						armJ = str(int(5*(round(int(rebar.LookupParameter('–ê—Ä–º_–ñ').AsValueString())/5))))
					except:
						armJ = '0'

					try:
						armAlpha = rebar.LookupParameter('–ê—Ä–º.–†–∞–∑–º–µ—ÄAlpha').AsValueString()
						armAlpha = armAlpha.split(' ')[0]
					except:
						armAlpha = '0'
						#armG_l.append('0')
					if mark not in mark_list:
						#print(mark)
						result.append([rebar, sh, type, mark, armA, armB,armV,armG, armD, armE, armJ, armAlpha])
						#TaskDialog.Show('1', str(arm_mark))
						mark_list.append(mark)
				except:
					0
			new_rebar_list =[]
			mark_list=[]
			#TaskDialog.Show('Done', str('–£—Å–ø—ñ—à–Ω–æ —Å—Ç–≤–æ—Ä–µ–Ω–æ'))

			result = [x for x in result if x[1] != '01'] #–≤–∏–¥–∞–ª–ª–µ–Ω–Ω—è –ø—Ä—è–º–∏—Ö —Å—Ç—Ä–∏–∂–Ω—ñ–≤ –∑—ñ —Å–ø–∏—Å–∫—É
			result_f = []
			#TaskDialog.Show('1', str(len(result)))
			for sublist in result: #–≤–∏–ª–∞–ª—è—é –¥—É–±–ª—ñ–∫–∞—Ç–∏
				if sublist not in result_f:
					if sublist[3] not in mark_list:
						mark_list.append(sublist[3])
						result_f.append(sublist)
			result_f.sort(key=lambda x: x[3])#—Å–æ—Ä—Ç—É–≤–∞–Ω–Ω—è —Å–ø–∏—Å–∫—É –∞—Ä–º–∞—Ç—É—Ä–∏ –ø–æ –º–∞—Ä—Ü—ñ


			count_1 = 0
			x_change_pos = []
			for p in position_list:
				if round(position_list[count_1][0].X, 5) != round(position_list[count_1-1][0].X, 5):
					x_change_pos.append(count_1)
				count_1 += 1
			count_1 = 0
			final_position_list = []
			x_pos = 0
			y_pos = -240/304.8
			for p in position_list:
				if count_1 == 0:
					final_position_list.append(XYZ(0, y_pos, 0))
				else:
					if count_1 not in x_change_pos:
						y_pos -= 240/304.8
						final_position_list.append(XYZ(x_pos, y_pos, 0))
					else:
						y_pos = -240/304.8
						x_pos += 870/304.8
						final_position_list.append(XYZ(x_pos, y_pos, 0))

				count_1 += 1
			count_position = 0
			if len(final_position_list) == 0:
				final_position_list.append(XYZ(0, -240/304.8, 0))

			#TaskDialog.Show('Done', str(result_f))
			for i in result_f: #–ø—Ä–∏–±–∏—Ä–∞—é –Ω—É–ª—ñ –∑ –º–∞—Ä–æ–∫ –≤—ñ–¥ 1 –¥–æ 9
				if i[3] != None:
					s = i[3]
					s = [c for c in s]
					#i[3]=i[3]+s[0]
					if s[0]=='0':
						s.pop(0)
						i[3]=s[0]
			detail_det_k = None
			views = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Views).WhereElementIsNotElementType().ToElements()
			for x in views:
				name_x = x.get_Parameter(BuiltInParameter.VIEW_NAME).AsString()
				#list_schedules.append(name_s)
				if name_x == "–ö–ë1.-3100.–ö–æ–ª–æ–Ω–∞ –ö1.1 –î–µ—Ç–∞–ª—ñ":
					detail_det_k = x

			#–°—Ç–≤–æ—Ä—é—é –≤—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π –∫—Ä–µ—Å–ª—è—Ä—Å—å–∫–∏–π –≤–∏–¥----------
			if len(s_filter) == 0:
				view_num = curview.get_Parameter(BuiltInParameter.VIEWPORT_SHEET_NUMBER).AsString()
			else:
				view_num = curview.get_Parameter(BuiltInParameter.SHEET_NUMBER).AsString()
			for sheet in sheets:
				sheet_num = sheet.get_Parameter(BuiltInParameter.SHEET_NUMBER).AsString()
				if view_num == sheet_num:
					sheet_id = sheet
					break
			if status == 'create':
				detail_det_k_new = detail_det_k.Duplicate(ViewDuplicateOption.Duplicate)
				detail_create = doc.GetElement(detail_det_k_new)

			#---------------------------------------------------
			#—Å—Ç–≤–æ—Ä—é—é –ø–æ–ª—è –Ω–∞ –∫—Ä–µ—Å–ª—è—Ä—Å—å–∫–æ–º—É –≤–∏–¥—ñ –≤—ñ–¥–æ–º–æ—Å—Ç—ñ –¥–µ—Ç–∞–ª—ñ
			h_line = 240/304.8
			r0=det_line('–î–µ—Ç0')

			"""
			if self.radio_1.IsChecked:
				filter_type = 'marka'
			elif self.radio_2.IsChecked:
				filter_type = 'mrk_con'
			elif self.radio_3.IsChecked:
				filter_type = 'mrk_izd'
			"""
			r0.Activate()
			doc.Regenerate()
			if status == 'create':
				newdet = doc.Create.NewFamilyInstance(XYZ(0,0,0), r0, detail_create)
				r0_comment = newdet.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS)
				r0_comment.Set(('{}*/{}*/{}*/{}').format(s_filter, filter_type, one_cons, arm_vupysk))

			count = a_1+b_1
			result_det = []

			for r in result_f:

				result_det.append(r)
				forma = r[1]
				r1 = det_line('Shape_'+ forma)
				if r1 != 0:
					r1.Activate()
					doc.Regenerate()
					#arm_param('Shape_'+ forma, r)
					#TaskDialog.Show('Done', '1')
					if status == 'create':
						newdet = doc.Create.NewFamilyInstance(XYZ(0,-h_line,0), r1, detail_create)
					else:
						if len(final_position_list) <= count_position: #—è–∫—â–æ —Å–ø–∏—Å–æ–∫ –∑–∞–∫—ñ–Ω—á–∏–≤—Å—è –¥–æ–¥–∞—é –ø–æ –£ –Ω–æ–≤—É –∫–æ–æ—Ä–¥–∏–Ω–∞—Ç—É
							old_xyz = final_position_list[count_position-1]
							new_xyz = XYZ(old_xyz.X, old_xyz.Y - 240/304.8, old_xyz.Z)
							final_position_list.append(new_xyz)
						newdet = doc.Create.NewFamilyInstance(final_position_list[count_position], r1, detail_create)

					h_line+=240/304.8
					arm_mark=r[3]
					#TaskDialog.Show('Done', '2')
					try:
						prefix = r[0].LookupParameter('–ê—Ä–º.–ü—Ä–µ—Ñ–∏–∫—Å–§–æ—Ä–º—ã')
						if prefix != None:
						    prefix = prefix.AsString()
						    arm_mark = prefix+arm_mark
					except:
						0
					arm_a_set=r[4]
					arm_b_set=r[5]
					arm_v_set=r[6]
					arm_g_set=r[7]
					arm_d_set=r[8]
					arm_e_set=r[9]
					arm_j_set=r[10]
					arm_alpha=r[11]
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º–ê')
						arm_det.Set(arm_a_set)
					except:
						0
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º–ë')
						arm_det.Set(arm_b_set)
					except:
						0
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º–í')
						arm_det.Set(arm_v_set)
					except:
						0
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º–ì')
						arm_det.Set(arm_g_set)
					except:
						0
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º–î')
						arm_det.Set(arm_d_set)
					except:
						0
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º–ï')
						arm_det.Set(arm_e_set)
					except:
						0
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º–ñ')
						arm_det.Set(arm_j_set)
					except:
						0
					try:
						arm_det = newdet.LookupParameter('–ê—Ä–º_–ú–∞—Ä–∫–∞')
						arm_det.Set(str(arm_mark))
					except:
						0
					result_det=[]

				else:
					print('–ù–µ–≤—ñ—Ä–Ω–æ –∑–∞–¥–∞–Ω–∞ —Ñ–æ—Ä–º–∞, –º–∞—Ä–∫–∞ —Å—Ç—Ä–∏–∂–Ω—è '+r[3])
				count_position+=1

			if status == 'create':
				d_k = Viewport.Create(doc, sheet_id.Id, detail_det_k_new, XYZ(0,0,0))
				d_k_name = doc.GetElement(detail_det_k_new).get_Parameter(BuiltInParameter.VIEW_NAME)
				d_k_name.Set(s_name.split('*/')[2] + '_–í—ñ–¥–æ–º—ñ—Å—Ç—å –¥–µ—Ç–∞–ª–µ–π')
				d_k_tom = doc.GetElement(detail_det_k_new).LookupParameter("–û—Ä–≥.–ö–æ–º–ø–ª–µ–∫—Ç–ö—Ä–µ—Å–ª–µ–Ω—å")
				if d_k_tom != None:
					d_k_tom.Set(s_name.split('*/')[0])
				d_k_tom2 = doc.GetElement(detail_det_k_new).LookupParameter("–û—Ä–≥.–í—ñ–¥–º—ñ—Ç–∫–∞")
				if d_k_tom2 != None:
					d_k_tom2.Set(s_name.split('*/')[1])
			t.Commit()
		else:
			t.RollBack()

	def print_mes(self):
		TaskDialog.Show('1','1')

	def Button_Ok(self, sender, e):
		try:
			customizable_event.raise_event(self.create_detail, ['create'])
		except:
			TaskDialog.Show('error','error')

	def Button_Refresh(self, sender, e):
		try:
			customizable_event.raise_event(self.create_detail, ['refresh'])
		except:
			TaskDialog.Show('error2','error2')

	def Button_Read(self, sender, e):
		try:
			customizable_event.raise_event(self.read_filter)
		except:
			TaskDialog.Show('error3','error3')
	def Button_Write(self, sender, e):
		try:
			customizable_event.raise_event(self.write_filter)
		except:
			TaskDialog.Show('error4','error4')

	def radio_1_button(self, sender, e):
		self.radio_2.IsChecked = False
		self.radio_3.IsChecked = False

	def radio_2_button(self, sender, e):
		self.radio_1.IsChecked = False
		self.radio_3.IsChecked = False

	def radio_3_button(self, sender, e):
		self.radio_1.IsChecked = False
		self.radio_2.IsChecked = False
# Let's launch our beautiful and useful form !
#print(1)

# üü¢ RUN WPF

modeless_form = ModelessForm("interface.xaml")




# ‚ïî‚ïê‚ïó‚ï¶  ‚ïî‚ïê‚ïó‚ïî‚ïê‚ïó‚ïî‚ïê‚ïó‚ïî‚ïê‚ïó‚ïî‚ïê‚ïó
# ‚ïë  ‚ïë  ‚ï†‚ïê‚ï£‚ïö‚ïê‚ïó‚ïö‚ïê‚ïó‚ïë‚ï£ ‚ïö‚ïê‚ïó
# ‚ïö‚ïê‚ïù‚ï©‚ïê‚ïù‚ï© ‚ï©‚ïö‚ïê‚ïù‚ïö‚ïê‚ïù‚ïö‚ïê‚ïù‚ïö‚ïê‚ïù CLASSES
# ===========================================================================


# ‚ïî‚ï¶‚ïó‚ïî‚ïê‚ïó‚ï¶‚ïî‚ïó‚ïî
# ‚ïë‚ïë‚ïë‚ï†‚ïê‚ï£‚ïë‚ïë‚ïë‚ïë
# ‚ï© ‚ï©‚ï© ‚ï©‚ï©‚ïù‚ïö‚ïù MAIN
# ===========================================================================



# # üîì Start Transaction
# t = Transaction(doc, __title__)
# t.Start()
#
#
#
#
#
#
#
#
#
#
#
#
#
# # üîí End Transaction
# t.Commit()

